name: Build master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      working-directory: ./src
      run: make
    - name: find
      run: find . -name c2tzx
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          ./src/c2tzx
        args: './src/c2tzx'
